name: Kellen
favicon: null
layout_spectrum: 0.38313552737236023
typography_spectrum: 0.20801164535805583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58595b'
    - '#949599'
    - '#8ec448'
    - '#2277ba'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.4643579232506454
purpose: []
